In [5]:
import numpy as np
# [1,2,3,"a"] + 1

x = np.array([1,2,3])
# print(x + 1)
x

'hello world'

In [6]:
x = list(range(10))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
import numpy as np

x = np.array(x)
type(x)

numpy.ndarray

In [11]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
x = list(range(10))
x[]

[3]

In [19]:
x[3]

3

In [60]:
x = np.arange(3**4).reshape(3,3,3,3)

x[0,0,0,0]


0

In [35]:
x[z,y,x]

16

In [111]:
x = (np.arange(3**2)+1).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
x = list(range(5))
x, x[::3]

([0, 1, 2, 3, 4], [0, 3])

In [116]:
x = [i for i in range(10_000_000)]

In [117]:
%time [i + 1 for i in x]

"done"

CPU times: total: 391 ms
Wall time: 1.7 s


'done'

In [118]:
arry = np.array(x)
%time arry + 1

CPU times: total: 0 ns
Wall time: 36.6 ms


array([       1,        2,        3, ...,  9999998,  9999999, 10000000])

In [ ]:
[1920,1080,3]
[0-255]

In [121]:
3840*2160*3*32

796262400